services:
  sdk:
    container_name: net-sdk
    tty: true
    stdin_open: true
    build:
      context: .
    volumes:
      - ~/Sources/chat/src:/source/chat
      - asp-bin:/source/chat/asp/bin/Release/net10.0/publish
      - wcf-bin:/source/chat/wcf/bin/Release/net10.0/publish

  runtime:
    container_name: aspnet-runtime
    tty: true
    stdin_open: true
    image: mcr.microsoft.com/dotnet/aspnet:10.0-azurelinux3.0
    ports:
      - 80:8080
    volumes:
      - asp-bin:/app/chat/asp/
      - wcf-bin:/app/chat/wcf/
volumes:
  asp-bin:
  wcf-bin: